version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: chatboat-postgres
    environment:
      POSTGRES_DB: chatboat
      POSTGRES_USER: chatboat
      POSTGRES_PASSWORD: chatboat123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - /Users/jeonghwanpark/Enviroment/chat-boat-pg-data:/var/lib/postgresql/data
    networks:
      - chatboat-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatboat -d chatboat"]
      interval: 10s
      timeout: 5s
      retries: 5

  chatboat-app:
    build: .
    container_name: chatboat-app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: chatboat
      DB_PASSWORD: chatboat123
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "2800:2800"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - chatboat-network
    restart: unless-stopped

networks:
  chatboat-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
