

spring:
  application:
    name: chatboat
  
  # PostgreSQL 데이터베이스 설정
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/chatboat
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:chatboat}
    password: ${DB_PASSWORD:chatboat123}
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Seoul
  
  # H2 콘솔 비활성화 (PostgreSQL 사용)
  h2:
    console:
      enabled: false

server:
  port: 2800

# OpenAI API 설정
openai:
  api-key: ${OPENAI_API_KEY:your-api-key-here}
  model: gpt-4o
  max-tokens: 2000
  temperature: 0.7

# PDF 업로드 설정
app:
  pdf:
    upload-dir: /app/uploads/pdf
